### ISSUE TITLE
Error while Gradle build

### ISSUE THREAD

**Issue by lalitsonawane** [AkshayChordiya/android-arch-news-sample#1]
Could not get unknown property 'NEWS_API_KEY' for ProductFlavor_Decorated{name=main, dimension=null, minSdkVersion=DefaultApiVersion{mApiLevel=15, mCodename='null'}, targetSdkVersion=null, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=1, versionName=1.0, applicationId=com.akshay.newsapp, testApplicationId=null, testInstrumentationRunner=android.support.test.runner.AndroidJUnitRunner, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.ProductFlavor. Open File

**Comment by lalitsonawane** [comment]
Gradle.Properties file not available in file structure.

**Comment by AkshayChordiya** [comment]
You need to add `NEWS_API_KEY` in your `gradle.properties` for Gradle to build.
Kindly go through the following [steps](https://github.com/AkshayChordiya/android-arch-news-sample#steps-to-run) to generate key for your app.

**Comment by lalitsonawane** [comment]
Hi Akshay,

Basically the graddle.properties file is not available in the project.

**Comment by AkshayChordiya** [comment]
Android Studio should have made the file for you if not then manually create the file and add this line:

NEWS_API_KEY = "YOUR_API_KEY"
