### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Rakhimjon** [AkshayChordiya/android-arch-news-sample#14]
I am runnig app this error : Program type already present: android.support.v4.os.ResultReceiver
Message{kind=ERROR, text=Program type already present: android.support.v4.os.ResultReceiver, sources=[Unknown source file], tool name=Optional.of(D8)}
 what is this akshay please help me

**Comment by AkshayChordiya** [comment]
Are you getting this error while compiling the code or it's a run-time issue?

**Comment by Rakhimjon** [comment]
run time issue

**Comment by AkshayChordiya** [comment]
Closing this issue due to no updates.
