### ISSUE TITLE
Getting "An annotation argument must be a compile-time constant"

### ISSUE THREAD

**Issue by duplex143** [AkshayChordiya/android-arch-news-sample#15]
I'm getting the above error at
`@GET("articles?source=google-news&apiKey=" + BuildConfig.NEWS_API_KEY)` in `NewsSourceService.kt`

**Comment by AkshayChordiya** [comment]
Did you add the `NEWS_API_KEY` in the `gradle.properties`?

**Comment by duplex143** [comment]
Yes

**Comment by AkshayChordiya** [comment]
Okay. Something is weird. Is this issue happening when you clone this project or on a newer project which you made?
Also make sure there is no error shown for `BuildConfig` and it's imported.

**Comment by duplex143** [comment]
Apologies. Added `NEWS_API_KEY=12345678` instead of `NEWS_API_KEY="12345678"`
Missed `"`
Nice app. Thanks.

**Comment by AkshayChordiya** [comment]
Sure. No problem.
