### ISSUE TITLE
ERROR: [TAG] Failed to resolve variable '${project.version}'

### ISSUE THREAD

**Issue by meidikawardana** [AkshayChordiya/android-arch-news-sample#17]
Just report this error when I already successfull to run this app on an android emulator.  I curious, what is the cause of this error? but app can running successfully on emulator
![error_news_app](https://user-images.githubusercontent.com/2024380/49775839-2111c080-fd2c-11e8-8a3c-df896c4f885b.PNG)

**Comment by AkshayChordiya** [comment]
Doesn't look like it's specific to this project. Did you check on StackOverFlow or tried cloning the project again?

**Comment by meidikawardana** [comment]
I clone the project directly from here. then I changed several things so the project can running successfully. here are the changes I applied: https://github.com/AkshayChordiya/android-arch-news-sample/issues/16#issuecomment-446056609

**Comment by meidikawardana** [comment]
please be noted, I am using android studio 3.2.1, @AkshayChordiya

**Comment by AkshayChordiya** [comment]
I think it's because in the latest commit. I migrated the dependencies to AndroidX and there are several issues on StackOverFlow like this:
https://stackoverflow.com/questions/52816022/failed-to-resolve-variable-project-groupid

Try to check it and solve from your side. Meanwhile I'll update the repository soon from side which might fix it for you.

**Comment by meidikawardana** [comment]
thank you, @AkshayChordiya . last time I opened & ran the project, the error already gone. but this error will make any newbie confused, so I suggest you to fix it.

**Comment by sundharsk** [comment]
i too got the same error ..
![Capture3](https://user-images.githubusercontent.com/46772827/54254932-d21e3600-457b-11e9-8639-9202fdf8cd98.PNG)

**Comment by AkshayChordiya** [comment]
I have fixed these issues. I'm closing this issue and if you still face the issue then feel free to re-open the issue.

**Comment by renderjaviii** [comment]
Could you give me a guide on how to specifically solve this error "[TAG] Failed to resolve variable '$ {project.version}'"

**Comment by jerrychong25** [comment]
Have same issue here too.

`ERROR: [TAG] Failed to resolve variable '${project.version}'`

How to fix this?

Thanks.

**Comment by AkshayChordiya** [comment]
I have tried again to fix, searching on SO gave me clue that it would be related to AndroidX and not to mention that the project needed to embrace AndroidX since a long time
