### ISSUE TITLE
 Integrate with Dagger 2

### ISSUE THREAD

**Issue by Ezike** [AkshayChordiya/android-arch-news-sample#20]
Add dagger 2 for dependency injection. I'd like to send a pr for this soon

**Comment by Ezike** [comment]
Hey Akshay,
I sent a PR for the dagger implementations. I'm trying to get used to open source contributions 🙂
I'll love to get your honest feedback. Thanks

**Comment by Ezike** [comment]
🙂 Thanks for the sssihjme

**Comment by AkshayChordiya** [comment]
I'm following the same pattern. Why did you close the issue?

**Comment by Ezike** [comment]
Oh I think its a mistake or an error.. Let me reopen it
